openapi: 3.2.0
info:
  title: BlueConic REST API v2 Group Types API
  description: Welcome to the BlueConic REST API v2.
  termsOfService: https://www.blueconic.com/blueconic-terms-and-conditions
  contact:
    name: Contact us
    url: https://support.blueconic.com/hc/en-us/requests/new
  license:
    name: BlueConic
    url: https://github.com/blueconic/openapi/blob/main/LICENSE.MD
  version: '100.0'
servers:
- url: https://{blueconicHostname}/rest/v2
  description: The BlueConic server
  variables:
    blueconicHostname:
      description: BlueConic server hostname, e.g. 'tenant.blueconic.net'
      default: tenantname
tags:
- name: Group Types
  description: Retrieve all types of groups, such as “Househould” or “Account”. Each group type has its own properties that can be used for segmentation. Read more
paths:
  /groupTypes:
    get:
      tags:
      - Group Types
      summary: Retrieves all types of groups
      description: Retrieves all group types.
      operationId: getAllGroupTypes
      responses:
        '200':
          description: Retrieves all types of groups.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/groupTypes'
              examples:
                Example group types response:
                  description: Example group types response
                  value: "{\n  \"groupTypes\": [\n    {\n      \"id\": \"company\",\n      \"name\": \"company\",\n      \"pluralName\": \"companies\"\n    }\n  ],\n  \"itemsPerPage\": 1,\n  \"startIndex\": 0,\n  \"totalPages\": 1,\n  \"totalResults\": 1\n}"
        '401':
          description: Authentication failed (unauthorized).
        '503':
          description: The server is too busy to handle the request.
      security:
      - oauth2:
        - read:group-types
components:
  schemas:
    groupType:
      type: object
      properties:
        id:
          type: string
          description: The ID of the group type
          example: household
        name:
          type: string
          description: Singular name of the group type
          example: Household
        pluralName:
          type: string
          description: Plural name of the group type
          example: Households
    groupTypes:
      type: object
      properties:
        groupTypes:
          type: array
          items:
            $ref: '#/components/schemas/groupType'
        itemsPerPage:
          type: integer
          format: int32
          description: Number of results per page.
          readOnly: true
        startIndex:
          type: integer
          format: int32
          description: The start index.
          readOnly: true
        totalPages:
          type: integer
          format: int32
          description: The total number of pages.
          readOnly: true
        totalResults:
          type: integer
          format: int32
          description: The total number of results.
          readOnly: true
  securitySchemes:
    oauth2:
      type: oauth2
      description: 'Authenticates a registered OAuth 2.0 client. The Authorization code flow and Client credentials flow are supported. Make sure to select the correct flow based on which flow the registered client supports. The client id and client secret can be found in BlueConic by opening the registered client under *Settings* > *Access management* > *Applications*.<br/>**NOTE:** When using the Authorization code flow, the redirect URL of the registered client in BlueConic must be set to `https://rest.apidoc.blueconic.com/oauth-receiver.html` and ''Send Proof Key for Code Exchange'' must be enabled.<br/><br/>To use a Bearer token for authentication, follow these steps: <br/>1. Acquire the token through authentication.<br/>2. Include the token in the request''s Authorization header as Bearer \<token\>.<br/>3. Send the request to access protected resources.<br/>4. Handle token expiration by refreshing or obtaining a new token.'
      flows:
        clientCredentials:
          tokenUrl: /rest/v2/oauth/token
        authorizationCode:
          authorizationUrl: /rest/v2/oauth/authorize
          tokenUrl: /rest/v2/oauth/token
          refreshUrl: /rest/v2/oauth/token
