openapi: 3.2.0
info:
  title: BlueConic REST API v2 URL mappings API
  description: Welcome to the BlueConic REST API v2.
  termsOfService: https://www.blueconic.com/blueconic-terms-and-conditions
  contact:
    name: Contact us
    url: https://support.blueconic.com/hc/en-us/requests/new
  license:
    name: BlueConic
    url: https://github.com/blueconic/openapi/blob/main/LICENSE.MD
  version: '100.0'
servers:
- url: https://{blueconicHostname}/rest/v2
  description: The BlueConic server
  variables:
    blueconicHostname:
      description: BlueConic server hostname, e.g. 'tenant.blueconic.net'
      default: tenantname
tags:
- name: URL mappings
  description: The following methods allow you to create, modify, and retrieve URL mappings (tracking pixel or shortened URL). These can be created via the External tracker tab, but can also be created as a separate object (not visible in the UI) via this REST API directly. You can use external trackers to track customer or visitor activity outside domains in your BlueConic tenant. Read more.
paths:
  /urlmappings:
    post:
      tags:
      - URL mappings
      summary: Create URL mapping
      description: Create a new URL mapping (separate from an external tracker).
      operationId: createURLMapping
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/urlmapping'
            examples:
              Urlmapping example body:
                description: Urlmapping example body
                value: "{\n  \"id\": \"2D\",\n  \"properties\": [\n    {\n      \"id\": \"pp_download\",\n      \"values\": [\n        \"Blueconic Release News R30\"\n      ]\n    },\n    {\n      \"id\": \"interactionId\",\n      \"values\": [\n        \"9197fdf7-e1d4-4b4b-8b59-5c49a72a412b\"\n      ]\n    },\n    {\n      \"id\": \"containerId\",\n      \"values\": [\n        \"b8bf7a5b-e937-451f-a93c-aa83a20deea5\"\n      ]\n    },\n    {\n      \"id\": \"channelId\",\n      \"values\": [\n        \"36a43edb-0a92-42df-8f19-f788cb146bda\"\n      ]\n    },\n    {\n      \"id\": \"pp_interest_index\",\n      \"values\": [\n        \"blueconic\"\n      ]\n    }\n  ],\n  \"type\": \"TRACKINGPIXEL\",\n  \"url\": \"http://www.blueconic.com/support/release-notes/profile-property-creation.htm\"\n}"
        required: true
      responses:
        '200':
          description: Returns the created urlmapping.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/urlmapping'
              examples:
                Example POST response:
                  description: Example POST response
                  value: "{\n  \"id\": \"2D\",\n  \"properties\": [\n    {\n      \"id\": \"pp_download\",\n      \"values\": [\n        \"Blueconic Release News R30\"\n      ]\n    },\n    {\n      \"id\": \"interactionId\",\n      \"values\": [\n        \"9197fdf7-e1d4-4b4b-8b59-5c49a72a412b\"\n      ]\n    },\n    {\n      \"id\": \"containerId\",\n      \"values\": [\n        \"b8bf7a5b-e937-451f-a93c-aa83a20deea5\"\n      ]\n    },\n    {\n      \"id\": \"channelId\",\n      \"values\": [\n        \"36a43edb-0a92-42df-8f19-f788cb146bda\"\n      ]\n    },\n    {\n      \"id\": \"pp_interest_index\",\n      \"values\": [\n        \"blueconic\"\n      ]\n    }\n  ],\n  \"type\": \"TRACKINGPIXEL\",\n  \"url\": \"http://www.blueconic.com/support/release-notes/profile-property-creation.htm\"\n}"
        '400':
          description: One or more required parameters are missing or invalid.
        '401':
          description: Authentication failed (unauthorized).
        '503':
          description: The server is too busy to handle the request.
      security:
      - oauth2:
        - write:url-mappings
  /urlmappings/{id}:
    get:
      tags:
      - URL mappings
      summary: Get URL mapping
      operationId: getOneURLMapping
      parameters:
      - name: id
        in: path
        description: The ID of the URL mapping.
        required: true
        schema:
          type: string
        example: 4Q
      responses:
        '200':
          description: Returns the URL mapping.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/urlmapping'
              examples:
                Example GET response:
                  description: Example GET response
                  value: "{\n  \"id\": \"4d\",\n  \"properties\": [\n    {\n      \"id\": \"pp_download\",\n      \"values\": [\n        \"Blueconic Release News R30\"\n      ]\n    },\n    {\n      \"id\": \"interactionId\",\n      \"values\": [\n        \"9197fdf7-e1d4-4b4b-8b59-5c49a72a412b\"\n      ]\n    },\n    {\n      \"id\": \"containerId\",\n      \"values\": [\n        \"b8bf7a5b-e937-451f-a93c-aa83a20deea5\"\n      ]\n    },\n    {\n      \"id\": \"channelId\",\n      \"values\": [\n        \"36a43edb-0a92-42df-8f19-f788cb146bda\"\n      ]\n    },\n    {\n      \"id\": \"pp_interest_index\",\n      \"values\": [\n        \"blueconic\"\n      ]\n    }\n  ],\n  \"type\": \"TRACKINGPIXEL\",\n  \"url\": \"http://www.blueconic.com/support/release-notes/profile-property-creation.htm\"\n}"
        '401':
          description: Authentication failed (unauthorized).
        '404':
          description: The specified URL mapping doesn't exist.
        '503':
          description: The server is too busy to handle the request.
      security:
      - oauth2:
        - read:url-mappings
    put:
      tags:
      - URL mappings
      summary: Update URL mapping
      operationId: updateURLMapping
      parameters:
      - name: id
        in: path
        description: The ID of the URL mapping.
        required: true
        schema:
          type: string
        example: 4Q
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/urlmapping'
            examples:
              URL mapping example body:
                description: URL mapping example body
                value: "{\n  \"id\": \"4d\",\n  \"properties\": [\n    {\n      \"id\": \"pp_download\",\n      \"values\": [\n        \"Blueconic Release News R30\"\n      ]\n    },\n    {\n      \"id\": \"interactionId\",\n      \"values\": [\n        \"9197fdf7-e1d4-4b4b-8b59-5c49a72a412b\"\n      ]\n    },\n    {\n      \"id\": \"containerId\",\n      \"values\": [\n        \"b8bf7a5b-e937-451f-a93c-aa83a20deea5\"\n      ]\n    }\n  ],\n  \"type\": \"TRACKINGPIXEL\",\n  \"url\": \"http://www.blueconic.com/support/release-notes/profile-property-creation.htm\"\n}"
        required: true
      responses:
        '200':
          description: Returns the updated urlmapping.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/urlmapping'
              examples:
                Example PUT response:
                  description: Example PUT response
                  value: "{\n  \"id\": \"4d\",\n  \"properties\": [\n    {\n      \"id\": \"pp_download\",\n      \"values\": [\n        \"Blueconic Release News R30\"\n      ]\n    },\n    {\n      \"id\": \"interactionId\",\n      \"values\": [\n        \"9197fdf7-e1d4-4b4b-8b59-5c49a72a412b\"\n      ]\n    },\n    {\n      \"id\": \"containerId\",\n      \"values\": [\n        \"b8bf7a5b-e937-451f-a93c-aa83a20deea5\"\n      ]\n    }\n  ],\n  \"type\": \"SHORTENEDURL\",\n  \"url\": \"https://support.blueconic.com/hc/en-us/categories/200063851-Release-Notes\"\n}"
        '401':
          description: Authentication failed (unauthorized).
        '404':
          description: The specified URL mapping doesn't exist.
        '503':
          description: The server is too busy to handle the request.
      security:
      - oauth2:
        - write:url-mappings
components:
  schemas:
    urlmapping:
      type: object
      properties:
        id:
          type: string
          description: The ID of shortened URL.
        properties:
          type: array
          description: List of profile properties to be set.
          items:
            $ref: '#/components/schemas/property'
        type:
          type: string
          description: The tracker must be one of the available types.
          enum:
          - TRACKINGPIXEL
          - SHORTENEDURL
        url:
          type: string
          description: The full URL of the target page (only applicable for type SHORTENEDURL).
      required:
      - id
      - properties
      - url
    property:
      type: object
      description: A property consisting of an ID and a list of values.
      properties:
        id:
          type: string
          description: The ID of the property.
        values:
          type: array
          description: Values for this property.
          items:
            type: string
            description: Values for this property.
  securitySchemes:
    oauth2:
      type: oauth2
      description: 'Authenticates a registered OAuth 2.0 client. The Authorization code flow and Client credentials flow are supported. Make sure to select the correct flow based on which flow the registered client supports. The client id and client secret can be found in BlueConic by opening the registered client under *Settings* > *Access management* > *Applications*.<br/>**NOTE:** When using the Authorization code flow, the redirect URL of the registered client in BlueConic must be set to `https://rest.apidoc.blueconic.com/oauth-receiver.html` and ''Send Proof Key for Code Exchange'' must be enabled.<br/><br/>To use a Bearer token for authentication, follow these steps: <br/>1. Acquire the token through authentication.<br/>2. Include the token in the request''s Authorization header as Bearer \<token\>.<br/>3. Send the request to access protected resources.<br/>4. Handle token expiration by refreshing or obtaining a new token.'
      flows:
        clientCredentials:
          tokenUrl: /rest/v2/oauth/token
        authorizationCode:
          authorizationUrl: /rest/v2/oauth/authorize
          tokenUrl: /rest/v2/oauth/token
          refreshUrl: /rest/v2/oauth/token
