openapi: 3.2.0
info:
  title: BlueConic REST API v2 Lifecycles API
  description: Welcome to the BlueConic REST API v2.
  termsOfService: https://www.blueconic.com/blueconic-terms-and-conditions
  contact:
    name: Contact us
    url: https://support.blueconic.com/hc/en-us/requests/new
  license:
    name: BlueConic
    url: https://github.com/blueconic/openapi/blob/main/LICENSE.MD
  version: '100.0'
servers:
- url: https://{blueconicHostname}/rest/v2
  description: The BlueConic server
  variables:
    blueconicHostname:
      description: BlueConic server hostname, e.g. 'tenant.blueconic.net'
      default: tenantname
tags:
- name: Lifecycles
  description: The following methods allow you to retrieve information about lifecycles. See Lifecycles.
paths:
  /lifecycles:
    get:
      tags:
      - Lifecycles
      summary: Get all lifecycles
      description: Retrieves all lifecycles.
      operationId: getAllLifecycles
      parameters:
      - name: startIndex
        in: query
        description: Specifies the index of the first item to include in the result.
        schema:
          type: integer
          format: int64
          default: 0
          example: 0
      - name: count
        in: query
        description: Specifies the number of results to return.
        schema:
          type: integer
          format: int64
          default: 20
          example: 10
      responses:
        '200':
          description: Returns the lifecycles.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lifecycle'
              examples:
                Response body:
                  description: Response body
                  value: "{\n  \"itemsPerPage\": 20,\n  \"lifecycles\": [\n    {\n      \"creationDate\": \"2025-09-24T08:40:14.740Z\",\n      \"creator\": {\n        \"fullName\": \"ondemand@blueconic.com\",\n        \"userName\": \"ondemand@blueconic.com\"\n      },\n      \"description\": \"\",\n      \"domains\": [],\n      \"id\": \"4d788b9e-49c7-4b58-aaab-d51d3c581bfe\",\n      \"lastModifiedDate\": \"2025-09-24T08:41:29.185Z\",\n      \"lastModifiedUser\": {\n        \"fullName\": \"ondemand@blueconic.com\",\n        \"userName\": \"ondemand@blueconic.com\"\n      },\n      \"name\": \"lifecycle1\",\n      \"pluginId\": \"lifecycle_blank\",\n      \"priority\": {\n        \"id\": \"912a4881-d480-40d3-af2c-af3b3d05709c\",\n        \"isDefault\": true,\n        \"name\": \"Medium\"\n      },\n      \"stages\": [\n        {\n          \"identifier\": \"94c78bcb-ef77-4313-a0d0-057515806ef0\",\n          \"name\": \"Profiles not assigned\",\n          \"rule\": {},\n          \"touchpoints\": []\n        },\n        {\n          \"identifier\": \"00cda648-2c39-4ed4-91ba-d5d7d95169e8\",\n          \"name\": \"First stage\",\n          \"rule\": {\n            \"frequencyCapDuration\": \"DAY\",\n            \"frequencyCapViews\": 3\n          },\n          \"touchpoints\": [\n            {\n              \"id\": \"45b88a3e-a91f-4a77-9b1d-dd79b76a46db\",\n              \"type\": \"dialogue\"\n            },\n            {\n              \"id\": \"0eebedf2-0b1a-46d0-bc08-d4ddd8857ed8\",\n              \"type\": \"dialogue\"\n            }\n          ]\n        }\n      ],\n      \"isEnabled\": true,\n      \"tags\": []\n    },\n    {\n      \"creationDate\": \"2025-09-24T08:41:17.589Z\",\n      \"creator\": {\n        \"fullName\": \"ondemand@blueconic.com\",\n        \"userName\": \"ondemand@blueconic.com\"\n      },\n      \"description\": \"\",\n      \"domains\": [],\n      \"id\": \"060cb60e-821c-4099-a084-37dcb8c8ad48\",\n      \"lastModifiedDate\": \"2025-09-24T08:41:17.589Z\",\n      \"lastModifiedUser\": {\n        \"fullName\": \"ondemand@blueconic.com\",\n        \"userName\": \"ondemand@blueconic.com\"\n      },\n      \"name\": \"lifecycle2\",\n      \"pluginId\": \"lifecycle_blank\",\n      \"priority\": {\n        \"id\": \"912a4881-d480-40d3-af2c-af3b3d05709c\",\n        \"isDefault\": true,\n        \"name\": \"Medium\"\n      },\n      \"stages\": [\n        {\n          \"identifier\": \"dddf5517-58a6-4df1-8ea7-8bfc9a190b7a\",\n          \"name\": \"Profiles not assigned\",\n          \"rule\": {},\n          \"touchpoints\": []\n        }\n      ],\n      \"isEnabled\": false,\n      \"tags\": []\n    }\n  ],\n  \"startIndex\": 0,\n  \"totalPages\": 1,\n  \"totalResults\": 2\n}"
        '401':
          description: Authentication failed (unauthorized).
        '403':
          description: Authorization failed (incorrect permissions).
        '503':
          description: The server is too busy to handle the request.
      security:
      - oauth2:
        - read:lifecycles
  /lifecycles/{lifecycle}:
    get:
      tags:
      - Lifecycles
      summary: Get one lifecycle
      description: Retrieves a single lifecycle.
      operationId: getOneLifecycle
      parameters:
      - name: lifecycle
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Returns the lifecycle.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lifecycle'
              examples:
                Response body:
                  description: Response body
                  value: "{\n  \"creationDate\": \"2025-09-24T08:40:14.740Z\",\n  \"creator\": {\n    \"fullName\": \"ondemand@blueconic.com\",\n    \"userName\": \"ondemand@blueconic.com\"\n  },\n  \"description\": \"\",\n  \"domains\": [],\n  \"id\": \"4d788b9e-49c7-4b58-aaab-d51d3c581bfe\",\n  \"lastModifiedDate\": \"2025-09-24T08:41:29.185Z\",\n  \"lastModifiedUser\": {\n    \"fullName\": \"ondemand@blueconic.com\",\n    \"userName\": \"ondemand@blueconic.com\"\n  },\n  \"name\": \"lifecycle1\",\n  \"pluginId\": \"lifecycle_blank\",\n  \"priority\": {\n    \"id\": \"912a4881-d480-40d3-af2c-af3b3d05709c\",\n    \"isDefault\": true,\n    \"name\": \"Medium\"\n  },\n  \"stages\": [\n    {\n      \"identifier\": \"94c78bcb-ef77-4313-a0d0-057515806ef0\",\n      \"name\": \"Profiles not assigned\",\n      \"rule\": {},\n      \"touchpoints\": []\n    },\n    {\n      \"identifier\": \"00cda648-2c39-4ed4-91ba-d5d7d95169e8\",\n      \"name\": \"First stage\",\n      \"rule\": {\n        \"frequencyCapDuration\": \"DAY\",\n        \"frequencyCapViews\": 3\n      },\n      \"touchpoints\": [\n        {\n          \"id\": \"45b88a3e-a91f-4a77-9b1d-dd79b76a46db\",\n          \"type\": \"dialogue\"\n        },\n        {\n          \"id\": \"0eebedf2-0b1a-46d0-bc08-d4ddd8857ed8\",\n          \"type\": \"dialogue\"\n        }\n      ]\n    }\n  ],\n  \"isEnabled\": true,\n  \"tags\": []\n}"
        '401':
          description: Authentication failed (unauthorized).
        '403':
          description: Authorization failed (incorrect permissions).
        '404':
          description: The lifecycle doesn't exist.
        '503':
          description: The server is too busy to handle the request.
      security:
      - oauth2:
        - read:lifecycles
components:
  schemas:
    simpleDomain:
      type: object
      description: The domain.
      properties:
        id:
          type: string
          description: Unique identifier.
        name:
          type: string
          description: Name of this object.
      readOnly: true
    UserBean:
      type: object
      description: BlueConic user.
      properties:
        fullName:
          type: string
          description: The full name of the user.
        userName:
          type: string
          description: The username.
      readOnly: true
    lifecycle:
      type: object
      properties:
        creationDate:
          type: string
          format: date-time
          description: The creation date of the object. Datetime in UTC in the https://www.ietf.org/rfc/rfc3339.txt format, example = "2025-01-22T11:21:33.872Z".
          readOnly: true
        creator:
          $ref: '#/components/schemas/UserBean'
        description:
          type: string
          description: The description.
        domains:
          type: array
          items:
            $ref: '#/components/schemas/simpleDomain'
        id:
          type: string
          description: The object ID.
        isEnabled:
          type: boolean
          description: Indicates whether it is enabled
        lastModifiedDate:
          type: string
          format: date-time
          description: The last modified date of the object. Datetime in UTC in the https://www.ietf.org/rfc/rfc3339.txt format, example = "2025-01-22T11:21:33.872Z".
          readOnly: true
        lastModifiedUser:
          $ref: '#/components/schemas/UserBean'
        name:
          type: string
          description: The object name.
        priority:
          $ref: '#/components/schemas/priority'
        stages:
          type: array
          items:
            $ref: '#/components/schemas/stage'
        tags:
          type: array
          description: The tags (i.e. labels).
          example: Address
          items:
            type: string
            description: The tags (i.e. labels).
            example: Address
    stage:
      type: object
      properties:
        identifier:
          type: string
          description: The ID of the stage.
        name:
          type: string
          description: The name of the stage.
        rule:
          $ref: '#/components/schemas/rule'
    rule:
      type: object
      properties:
        frequencyCapDuration:
          type: string
          description: The time period for the views cap.
          enum:
          - MINUTE
          - HOUR
          - DAY
          - WEEK
          - MONTH
          - QUARTER
          - YEAR
          - ALWAYS
          - SESSION
        frequencyCapViews:
          type: integer
          format: int32
          description: The number of views allowed in the specified time period.
        id:
          type: string
          description: The ID of the frequency rule.
    priority:
      type: object
      properties:
        id:
          type: string
          description: The ID of the priority.
        isDefault:
          type: boolean
          description: Whether the priority is the default priority.
        name:
          type: string
          description: The name of the priority.
  securitySchemes:
    oauth2:
      type: oauth2
      description: 'Authenticates a registered OAuth 2.0 client. The Authorization code flow and Client credentials flow are supported. Make sure to select the correct flow based on which flow the registered client supports. The client id and client secret can be found in BlueConic by opening the registered client under *Settings* > *Access management* > *Applications*.<br/>**NOTE:** When using the Authorization code flow, the redirect URL of the registered client in BlueConic must be set to `https://rest.apidoc.blueconic.com/oauth-receiver.html` and ''Send Proof Key for Code Exchange'' must be enabled.<br/><br/>To use a Bearer token for authentication, follow these steps: <br/>1. Acquire the token through authentication.<br/>2. Include the token in the request''s Authorization header as Bearer \<token\>.<br/>3. Send the request to access protected resources.<br/>4. Handle token expiration by refreshing or obtaining a new token.'
      flows:
        clientCredentials:
          tokenUrl: /rest/v2/oauth/token
        authorizationCode:
          authorizationUrl: /rest/v2/oauth/authorize
          tokenUrl: /rest/v2/oauth/token
          refreshUrl: /rest/v2/oauth/token
