openapi: 3.2.0
info:
  title: BlueConic REST API v2 Pageview events API
  description: Welcome to the BlueConic REST API v2.
  termsOfService: https://www.blueconic.com/blueconic-terms-and-conditions
  contact:
    name: Contact us
    url: https://support.blueconic.com/hc/en-us/requests/new
  license:
    name: BlueConic
    url: https://github.com/blueconic/openapi/blob/main/LICENSE.MD
  version: '100.0'
servers:
- url: https://{blueconicHostname}/rest/v2
  description: The BlueConic server
  variables:
    blueconicHostname:
      description: BlueConic server hostname, e.g. 'tenant.blueconic.net'
      default: tenantname
tags:
- name: Pageview events
  description: Pageview events are used to track page views by profiles. This is used by BlueConic Listeners. See Listeners and Trackers.
paths:
  /pageviewEvents:
    post:
      tags:
      - Pageview events
      summary: Create page view event
      description: Register that a profile visited a certain web page.
      operationId: createPageviewEvent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PageViewEventBean'
        required: true
      responses:
        '200':
          description: No specific content.
        '400':
          description: One or more required parameters are missing or invalid.
        '503':
          description: The server is too busy to handle the request.
components:
  schemas:
    PageViewEventBean:
      type: object
      properties:
        profileId:
          type: string
          description: The ID of the profile that triggered the event. For this profile, the properties "firstvisit", "visiteddomain" and "visitedchannel" are updated.
          example: 3bc7cc93-21bc-42d5-bede-dcb1a501fc16
        referrer:
          type: string
          description: The URL of the previous (referring) page.
          example: https://www.example.com/
        url:
          type: string
          description: The URL of the current page.
          example: https://www.example.com/
      required:
      - url
  securitySchemes:
    oauth2:
      type: oauth2
      description: 'Authenticates a registered OAuth 2.0 client. The Authorization code flow and Client credentials flow are supported. Make sure to select the correct flow based on which flow the registered client supports. The client id and client secret can be found in BlueConic by opening the registered client under *Settings* > *Access management* > *Applications*.<br/>**NOTE:** When using the Authorization code flow, the redirect URL of the registered client in BlueConic must be set to `https://rest.apidoc.blueconic.com/oauth-receiver.html` and ''Send Proof Key for Code Exchange'' must be enabled.<br/><br/>To use a Bearer token for authentication, follow these steps: <br/>1. Acquire the token through authentication.<br/>2. Include the token in the request''s Authorization header as Bearer \<token\>.<br/>3. Send the request to access protected resources.<br/>4. Handle token expiration by refreshing or obtaining a new token.'
      flows:
        clientCredentials:
          tokenUrl: /rest/v2/oauth/token
        authorizationCode:
          authorizationUrl: /rest/v2/oauth/authorize
          tokenUrl: /rest/v2/oauth/token
          refreshUrl: /rest/v2/oauth/token
