openapi: 3.2.0
info:
  title: BlueConic REST API v2 Notebooks API
  description: Welcome to the BlueConic REST API v2.
  termsOfService: https://www.blueconic.com/blueconic-terms-and-conditions
  contact:
    name: Contact us
    url: https://support.blueconic.com/hc/en-us/requests/new
  license:
    name: BlueConic
    url: https://github.com/blueconic/openapi/blob/main/LICENSE.MD
  version: '100.0'
servers:
- url: https://{blueconicHostname}/rest/v2
  description: The BlueConic server
  variables:
    blueconicHostname:
      description: BlueConic server hostname, e.g. 'tenant.blueconic.net'
      default: tenantname
tags:
- name: Notebooks
  description: The following methods allow you to retrieve AI Workbench notebooks and their run history. See AI Workbench Overview.
paths:
  /notebooks:
    get:
      tags:
      - Notebooks
      summary: Get all notebooks
      description: Retrieves all notebooks.
      operationId: getAllNotebooks
      parameters:
      - name: startIndex
        in: query
        description: Specifies the index of the first item to include in the result.
        schema:
          type: integer
          format: int64
          default: 0
          example: 0
      - name: count
        in: query
        description: Specifies the number of results to return.
        schema:
          type: integer
          format: int64
          default: 20
          example: 10
      responses:
        '200':
          description: Returns the notebooks.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notebooks'
              examples:
                Response body:
                  description: Response body
                  value: "{\n  \"itemsPerPage\": 10,\n  \"notebooks\": [\n    {\n      \"creationDate\": \"2025-09-23T07:39:27.040Z\",\n      \"creator\": {\n        \"fullName\": \"ondemand@blueconic.com\",\n        \"userName\": \"ondemand@blueconic.com\"\n      },\n      \"description\": \"\",\n      \"id\": \"f72deceb-c261-48ee-a355-56de0d37be92\",\n      \"lastModifiedDate\": \"2025-09-24T07:23:55.044Z\",\n      \"lastModifiedUser\": {\n        \"fullName\": \"ondemand@blueconic.com\",\n        \"userName\": \"ondemand@blueconic.com\"\n      },\n      \"lastRun\": {\n        \"endDate\": \"2025-09-23T07:43:34.567Z\",\n        \"goalStatistics\": [],\n        \"message\": \"<p>Notebook execution finished. <a href=\\\\\"/rest/v2/notebooks/f72deceb-c261-48ee-a355-56de0d37be92/executions/20250923074331_f72deceb-c261-48ee-a355-56de0d37be92/output?preview=true\\\\\">Preview</a>, <a href=\\\\\"/rest/v2/notebooks/f72deceb-c261-48ee-a355-56de0d37be92/executions/20250923074331_f72deceb-c261-48ee-a355-56de0d37be92/output?download=true\\\\\">JSON</a>, <a href=\\\\\"/rest/v2/notebooks/f72deceb-c261-48ee-a355-56de0d37be92/executions/20250923074331_f72deceb-c261-48ee-a355-56de0d37be92/log\\\\\">log</a></p>\",\n        \"runCount\": 2,\n        \"runId\": \"20250923074329_f72deceb-c261-48ee-a355-56de0d37be92\",\n        \"startDate\": \"2025-09-23T07:43:29.564Z\",\n        \"state\": \"FINISHED\"\n      },\n      \"name\": \"notebook1\",\n      \"pluginId\": \"notebook_blank\",\n      \"isEnabled\": false,\n      \"tags\": []\n    },\n    {\n      \"creationDate\": \"2025-09-24T07:24:00.877Z\",\n      \"creator\": {\n        \"fullName\": \"ondemand@blueconic.com\",\n        \"userName\": \"ondemand@blueconic.com\"\n      },\n      \"description\": \"\",\n      \"id\": \"072bc703-1958-423c-9def-10864ab08e73\",\n      \"lastModifiedDate\": \"2025-09-24T07:24:00.877Z\",\n      \"lastModifiedUser\": {\n        \"fullName\": \"ondemand@blueconic.com\",\n        \"userName\": \"ondemand@blueconic.com\"\n      },\n      \"name\": \"notebook2\",\n      \"pluginId\": \"notebook_blank\",\n      \"isEnabled\": true,\n      \"tags\": []\n    }\n  ],\n  \"startIndex\": 0,\n  \"totalPages\": 1,\n  \"totalResults\": 2\n}"
        '401':
          description: Authentication failed (unauthorized).
        '403':
          description: Authorization failed (incorrect permissions).
        '503':
          description: The server is too busy to handle the request.
      security:
      - oauth2:
        - read:notebooks
  /notebooks/{notebook}:
    get:
      tags:
      - Notebooks
      summary: Get one notebook
      description: Retrieves a single notebook.
      operationId: getOneNotebook
      parameters:
      - name: notebook
        in: path
        description: The ID of the notebook.
        required: true
        schema:
          type: string
        examples:
          UUID of the notebook:
            description: UUID of the notebook
            value: ce016360-28ae-4e05-952a-cb5f642cd2b7
      responses:
        '200':
          description: Returns the notebook.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notebook'
              examples:
                Response body:
                  description: Response body
                  value: "{\n  \"creationDate\": \"2025-09-23T07:39:27.040Z\",\n  \"creator\": {\n    \"fullName\": \"ondemand@blueconic.com\",\n    \"userName\": \"ondemand@blueconic.com\"\n  },\n  \"description\": \"\",\n  \"id\": \"f72deceb-c261-48ee-a355-56de0d37be92\",\n  \"lastModifiedDate\": \"2025-09-24T07:23:55.044Z\",\n  \"lastModifiedUser\": {\n    \"fullName\": \"ondemand@blueconic.com\",\n    \"userName\": \"ondemand@blueconic.com\"\n  },\n  \"lastRun\": {\n    \"endDate\": \"2025-09-23T07:43:34.567Z\",\n    \"goalStatistics\": [],\n    \"message\": \"<p>Notebook execution finished. <a href=\\\\\"/rest/v2/notebooks/f72deceb-c261-48ee-a355-56de0d37be92/executions/20250923074331_f72deceb-c261-48ee-a355-56de0d37be92/output?preview=true\\\\\">Preview</a>, <a href=\\\\\"/rest/v2/notebooks/f72deceb-c261-48ee-a355-56de0d37be92/executions/20250923074331_f72deceb-c261-48ee-a355-56de0d37be92/output?download=true\\\\\">JSON</a>, <a href=\\\\\"/rest/v2/notebooks/f72deceb-c261-48ee-a355-56de0d37be92/executions/20250923074331_f72deceb-c261-48ee-a355-56de0d37be92/log\\\\\">log</a></p>\",\n    \"runCount\": 2,\n    \"runId\": \"20250923074329_f72deceb-c261-48ee-a355-56de0d37be92\",\n    \"startDate\": \"2025-09-23T07:43:29.564Z\",\n    \"state\": \"FINISHED\"\n  },\n  \"name\": \"notebook1\",\n  \"pluginId\": \"notebook_blank\",\n  \"isEnabled\": false,\n  \"tags\": []\n}"
        '401':
          description: Authentication failed (unauthorized).
        '403':
          description: Authorization failed (incorrect permissions).
        '404':
          description: The notebook doesn't exist.
        '503':
          description: The server is too busy to handle the request.
      security:
      - oauth2:
        - read:notebooks
  /notebooks/{notebook}/runs:
    get:
      tags:
      - Notebooks
      summary: Get run history for a notebook
      description: Returns the run history of a notebook batch execution.
      operationId: getNotebookRunHistory
      parameters:
      - name: notebook
        in: path
        description: The ID of the notebook.
        required: true
        schema:
          type: string
        examples:
          UUID of the notebook:
            description: UUID of the notebook
            value: ce016360-28ae-4e05-952a-cb5f642cd2b7
      - name: startIndex
        in: query
        description: Specifies the index of the first item to include in the result.
        schema:
          type: integer
          format: int64
          default: 0
          example: 0
      - name: count
        in: query
        description: Specifies the number of results to return.
        schema:
          type: integer
          format: int64
          default: 20
          example: 10
      responses:
        '200':
          description: Returns the run history entries.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotebookStatusBeans'
              examples:
                Response body:
                  description: Response body
                  value: "{\n  \"runs\": [\n    {\n      \"endDate\": \"2025-09-23T07:43:34.567Z\",\n      \"goalStatistics\": [],\n      \"message\": \"<p>Notebook execution finished. <a href=\\\\\"/rest/v2/notebooks/f72deceb-c261-48ee-a355-56de0d37be92/executions/20250923074331_f72deceb-c261-48ee-a355-56de0d37be92/output?preview=true\\\\\">Preview</a>, <a href=\\\\\"/rest/v2/notebooks/f72deceb-c261-48ee-a355-56de0d37be92/executions/20250923074331_f72deceb-c261-48ee-a355-56de0d37be92/output?download=true\\\\\">JSON</a>, <a href=\\\\\"/rest/v2/notebooks/f72deceb-c261-48ee-a355-56de0d37be92/executions/20250923074331_f72deceb-c261-48ee-a355-56de0d37be92/log\\\\\">log</a></p>\",\n      \"runCount\": 2,\n      \"runId\": \"20250923074329_f72deceb-c261-48ee-a355-56de0d37be92\",\n      \"startDate\": \"2025-09-23T07:43:29.564Z\",\n      \"state\": \"FINISHED\"\n    },\n    {\n      \"endDate\": \"2025-09-23T07:43:07.609Z\",\n      \"goalStatistics\": [],\n      \"message\": \"<p>Notebook execution finished. <a href=\\\\\"/rest/v2/notebooks/f72deceb-c261-48ee-a355-56de0d37be92/executions/20250923074300_f72deceb-c261-48ee-a355-56de0d37be92/output?preview=true\\\\\">Preview</a>, <a href=\\\\\"/rest/v2/notebooks/f72deceb-c261-48ee-a355-56de0d37be92/executions/20250923074300_f72deceb-c261-48ee-a355-56de0d37be92/output?download=true\\\\\">JSON</a>, <a href=\\\\\"/rest/v2/notebooks/f72deceb-c261-48ee-a355-56de0d37be92/executions/20250923074300_f72deceb-c261-48ee-a355-56de0d37be92/log\\\\\">log</a></p>\",\n      \"runCount\": 1,\n      \"runId\": \"20250923074258_f72deceb-c261-48ee-a355-56de0d37be92\",\n      \"startDate\": \"2025-09-23T07:42:58.446Z\",\n      \"state\": \"FINISHED\"\n    }\n  ],\n  \"itemsPerPage\": 10,\n  \"startIndex\": 0,\n  \"totalPages\": 1,\n  \"totalResults\": 2\n}"
        '401':
          description: Authentication failed (unauthorized).
        '403':
          description: Authorization failed (incorrect permissions).
        '404':
          description: The notebook doesn't exist.
        '503':
          description: The server is too busy to handle the request.
      security:
      - oauth2:
        - read:notebooks
components:
  schemas:
    SimpleRoleBean:
      type: object
      description: A role with id and name.
      properties:
        id:
          type: string
          description: Unique identifier of the role.
        name:
          type: string
          description: Name of the role.
    status:
      type: object
      description: Notebook run status.
      properties:
        endDate:
          type: string
          format: date-time
          description: The end date of the run. Datetime in UTC in the https://www.ietf.org/rfc/rfc3339.txt format, example = "2025-01-22T11:21:33.872Z".
          readOnly: true
        goalStatistics:
          type: array
          description: The goal statistics
          items:
            $ref: '#/components/schemas/property'
        lane:
          type: string
          description: The lane in which this run was executed
          enum:
          - REGULAR
          - REGULAR2
          - REGULAR3
          - REGULAR4
          - REGULAR5
          - REGULAR6
          - REGULAR7
          - REGULAR8
          - EXPRESS
          - RUN_NOW
          - CONTINUOUS
        message:
          type: string
          description: The message of the run
        runCount:
          type: integer
          format: int64
          description: The run count
        runId:
          type: string
          description: The run id
        startDate:
          type: string
          format: date-time
          description: The start date of the run. Datetime in UTC in the https://www.ietf.org/rfc/rfc3339.txt format, example = "2025-01-22T11:21:33.872Z".
          readOnly: true
        state:
          type: string
          description: The state of the run
          enum:
          - STARTING
          - RUNNING
          - FINISHED
          - FAILED
          - STOPPING
          - STOPPED
    property:
      type: object
      description: A property consisting of an ID and a list of values.
      properties:
        id:
          type: string
          description: The ID of the property.
        values:
          type: array
          description: Values for this property.
          items:
            type: string
            description: Values for this property.
    UserBean:
      type: object
      description: BlueConic user.
      properties:
        fullName:
          type: string
          description: The full name of the user.
        userName:
          type: string
          description: The username.
      readOnly: true
    NotebookStatusBeans:
      type: object
      description: A collection of notebook run status entries.
      properties:
        entries:
          type: array
          description: List of notebook run status entries
          items:
            $ref: '#/components/schemas/status'
        itemsPerPage:
          type: integer
          format: int32
          description: Number of results per page.
          readOnly: true
        runs:
          type: array
          description: List of notebook run status entries
          items:
            $ref: '#/components/schemas/status'
        startIndex:
          type: integer
          format: int32
          description: The start index.
          readOnly: true
        totalPages:
          type: integer
          format: int32
          description: The total number of pages.
          readOnly: true
        totalResults:
          type: integer
          format: int32
          description: The total number of results.
          readOnly: true
    notebook:
      type: object
      properties:
        creationDate:
          type: string
          format: date-time
          description: The creation date of the object. Datetime in UTC in the https://www.ietf.org/rfc/rfc3339.txt format, example = "2025-01-22T11:21:33.872Z".
          readOnly: true
        creator:
          $ref: '#/components/schemas/UserBean'
        description:
          type: string
          description: The description.
        id:
          type: string
          description: The object ID.
        isEnabled:
          type: boolean
          description: Indicates whether it is enabled
        lastModifiedDate:
          type: string
          format: date-time
          description: The last modified date of the object. Datetime in UTC in the https://www.ietf.org/rfc/rfc3339.txt format, example = "2025-01-22T11:21:33.872Z".
          readOnly: true
        lastModifiedUser:
          $ref: '#/components/schemas/UserBean'
        lastRun:
          $ref: '#/components/schemas/status'
        name:
          type: string
          description: The object name.
        roles:
          type: array
          description: Roles allowed to edit this notebook; empty means no role-based restriction
          items:
            $ref: '#/components/schemas/SimpleRoleBean'
        tags:
          type: array
          description: The tags (i.e. labels).
          example: Address
          items:
            type: string
            description: The tags (i.e. labels).
            example: Address
      required:
      - roles
    notebooks:
      type: object
      properties:
        itemsPerPage:
          type: integer
          format: int32
          description: Number of results per page.
          readOnly: true
        notebooks:
          type: array
          items:
            $ref: '#/components/schemas/notebook'
        startIndex:
          type: integer
          format: int32
          description: The start index.
          readOnly: true
        totalPages:
          type: integer
          format: int32
          description: The total number of pages.
          readOnly: true
        totalResults:
          type: integer
          format: int32
          description: The total number of results.
          readOnly: true
  securitySchemes:
    oauth2:
      type: oauth2
      description: 'Authenticates a registered OAuth 2.0 client. The Authorization code flow and Client credentials flow are supported. Make sure to select the correct flow based on which flow the registered client supports. The client id and client secret can be found in BlueConic by opening the registered client under *Settings* > *Access management* > *Applications*.<br/>**NOTE:** When using the Authorization code flow, the redirect URL of the registered client in BlueConic must be set to `https://rest.apidoc.blueconic.com/oauth-receiver.html` and ''Send Proof Key for Code Exchange'' must be enabled.<br/><br/>To use a Bearer token for authentication, follow these steps: <br/>1. Acquire the token through authentication.<br/>2. Include the token in the request''s Authorization header as Bearer \<token\>.<br/>3. Send the request to access protected resources.<br/>4. Handle token expiration by refreshing or obtaining a new token.'
      flows:
        clientCredentials:
          tokenUrl: /rest/v2/oauth/token
        authorizationCode:
          authorizationUrl: /rest/v2/oauth/authorize
          tokenUrl: /rest/v2/oauth/token
          refreshUrl: /rest/v2/oauth/token
