openapi: 3.2.0
info:
  title: BlueConic REST API v2 Channels API
  description: Welcome to the BlueConic REST API v2.
  termsOfService: https://www.blueconic.com/blueconic-terms-and-conditions
  contact:
    name: Contact us
    url: https://support.blueconic.com/hc/en-us/requests/new
  license:
    name: BlueConic
    url: https://github.com/blueconic/openapi/blob/main/LICENSE.MD
  version: '100.0'
servers:
- url: https://{blueconicHostname}/rest/v2
  description: The BlueConic server
  variables:
    blueconicHostname:
      description: BlueConic server hostname, e.g. 'tenant.blueconic.net'
      default: tenantname
tags:
- name: Channels
  description: The Channel API allows you to retrieve information about channels in BlueConic.
paths:
  /channels:
    get:
      tags:
      - Channels
      summary: Get all channels
      description: Retrieves all channels.
      operationId: getAllChannels
      parameters:
      - name: startIndex
        in: query
        description: Specifies the index of the first result to return.
        schema:
          type: integer
          format: int32
        example: 0
      - name: count
        in: query
        description: Specifies the number of results to return.
        schema:
          type: integer
          format: int32
        example: 10
      responses:
        '200':
          description: Returns the channels.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelsV2Schema'
              examples:
                Example channels response:
                  description: Example channels response
                  value: "{\n  \"channels\" : [\n    {\n      \"aliases\" : [ \"blueconic.com\" ],\n      \"domain\": {\n        \"id\" : \"6398b714-45fd-4c28-ab08-80d8fea50757\",\n        \"name\" : \"blueconic.com\"\n      },\n      \"hostname\" : \"www.blueconic.com\",\n      \"id\" : \"6b44d80c-73c8-485b-ad76-b53a103751af\",\n      \"name\" : \"www.blueconic.com\",\n      \"tags\" : [ \"Marketing\", \"Data\", \"Privacy\" ],\n      \"type\" : \"WEBSITE\",\n      \"visitorCount\": 10\n    },\n    {\n      \"aliases\" : [ ],\n      \"domain\": {\n        \"id\" : \"6398b714-45fd-4c28-ab08-80d8fea50757\",\n        \"name\" : \"blueconic.com\"\n      },\n      \"hostname\" : \"ios://com.blueconic.app\",\n      \"id\" : \"9d7a7b63-7372-4d43-a67f-027a01918d64\",\n      \"name\" : \"BlueConic App\",\n      \"tags\" : [ \"Mobile\", \"Technology\" ],\n      \"type\" : \"MOBILE\",\n      \"visitorCount\": 2\n    },\n    {\n      \"aliases\" : [ ],\n      \"domain\": {\n        \"id\" : \"6398b714-45fd-4c28-ab08-80d8fea50757\",\n        \"name\" : \"blueconic.com\"\n      },\n      \"hostname\" : \"\",\n      \"id\" : \"e029bde2-3776-4985-a82c-090bf7e7673c\",\n      \"name\" : \"Newsletter\",\n      \"tags\" : [ \"Subscription\" ],\n      \"type\" : \"EMAIL\",\n      \"visitorCount\": 1\n    }\n  ],\n  \"itemsPerPage\" : 20,\n  \"startIndex\" : 0,\n  \"totalPages\" : 1,\n  \"totalResults\" : 3\n}"
        '401':
          description: Authentication failed (unauthorized).
        '503':
          description: The server is too busy to handle the request.
      security:
      - oauth2:
        - read:channels
  /channels/{channelId}:
    get:
      tags:
      - Channels
      summary: Get one channel
      description: Retrieves a single channel.
      operationId: getOneChannel
      parameters:
      - name: channelId
        in: path
        description: The ID of the channel.
        required: true
        schema:
          type: string
        example: 3b55d90d-91b8-263a-bd87-c43a104862ef
      responses:
        '200':
          description: Returns the channel.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/channel'
              examples:
                Example channel response:
                  description: Example channel response
                  value: "{\n  \"aliases\" : [ \"blueconic.com\" ],\n  \"creationDate\" : \"2024-01-24T12:30:50.000Z\",\n  \"creator\" : {\n    \"fullName\" : \"user@blueconic.com\",\n    \"userName\" : \"user@blueconic.com\"\n  },\n  \"description\" : \"BlueConic website\",\n  \"domain\": {\n    \"id\" : \"6398b714-45fd-4c28-ab08-80d8fea50757\",\n    \"name\" : \"www.blueconic.com\"\n  },\n  \"hostname\" : \"www.blueconic.com\",\n  \"id\" : \"6b44d80c-73c8-485b-ad76-b53a103751af\",\n  \"lastModifiedDate\" : \"2024-02-01T12:30:50.000Z\",\n  \"lastModifiedUser\" : {\n    \"fullName\" : \"user@blueconic.com\",\n    \"userName\" : \"user@blueconic.com\"\n  },\n  \"logo\" : \"https://bc.blueconic.net/rest/v2/channels/6b44d80c-73c8-485b-ad76-b53a103751af/logo?etag=3082b317eba5029e0aea03b42e3f3ca1\",\n  \"name\" : \"www.blueconic.com\",\n  \"tags\" : [ \"Marketing\", \"Data\", \"Privacy\" ],\n  \"type\" : \"WEBSITE\",\n  \"visitorCount\" : 10\n}"
        '400':
          description: One or more required parameters are missing or invalid.
        '404':
          description: Channel not found.
        '401':
          description: Authentication failed (unauthorized).
        '503':
          description: The server is too busy to handle the request.
      security:
      - oauth2:
        - read:channels
components:
  schemas:
    simpleDomain:
      type: object
      description: The domain.
      properties:
        id:
          type: string
          description: Unique identifier.
        name:
          type: string
          description: Name of this object.
      readOnly: true
    ChannelBeanV2SchemaForChannelsV2:
      type: object
      description: The channels.
      properties:
        aliases:
          type: array
          description: The aliases of the channel. Alternative hostnames, only applicable to web channels. For example, an alias of the hostname `www.blueconic.com` could be `blueconic.com`.
          items:
            type: string
            description: The aliases of the channel. Alternative hostnames, only applicable to web channels. For example, an alias of the hostname `www.blueconic.com` could be `blueconic.com`.
        domain:
          $ref: '#/components/schemas/simpleDomain'
        hostname:
          type: string
          description: The hostname of the channel. For web channels, the hostname of the website, excluding the protocol (e.g. `https://`) and path (e.g. `/`). For mobile/ctv channels, the App ID. For email channels, the hostname is empty.
        id:
          type: string
          description: The ID of the channel.
        name:
          type: string
          description: The name of the channel.
        tags:
          type: array
          description: The tags of the channel.
          items:
            type: string
            description: The tags of the channel.
        type:
          type: string
          description: The type of the channel.
          enum:
          - EMAIL
          - MOBILE
          - WEBSITE
          - CTV
        visitorCount:
          type: integer
          format: int32
          description: The visitor count of the channel.
    channel:
      type: object
      properties:
        aliases:
          type: array
          description: The aliases of the channel. Alternative hostnames, only applicable to web channels. For example, an alias of the hostname `www.blueconic.com` could be `blueconic.com`.
          items:
            type: string
            description: The aliases of the channel. Alternative hostnames, only applicable to web channels. For example, an alias of the hostname `www.blueconic.com` could be `blueconic.com`.
          uniqueItems: true
        creationDate:
          type: string
          format: date-time
          description: The creation date of the object. Datetime in UTC in the https://www.ietf.org/rfc/rfc3339.txt format, example = "2025-01-22T11:21:33.872Z".
          readOnly: true
        creator:
          $ref: '#/components/schemas/UserBean'
        description:
          type: string
          description: The description.
        domain:
          $ref: '#/components/schemas/simpleDomain'
        hostname:
          type: string
          description: The hostname of the channel. For web channels, the hostname of the website, excluding the protocol (e.g. `https://`) and path (e.g. `/`). For mobile channels, the App ID. For email channels, the hostname is empty.
        id:
          type: string
          description: The object ID.
        lastModifiedDate:
          type: string
          format: date-time
          description: The last modified date of the object. Datetime in UTC in the https://www.ietf.org/rfc/rfc3339.txt format, example = "2025-01-22T11:21:33.872Z".
          readOnly: true
        lastModifiedUser:
          $ref: '#/components/schemas/UserBean'
        lastVisitedDate:
          type: string
          format: date-time
          description: The date and time when the channel was last visited.
        logo:
          type: string
          description: The channel logo link.
        name:
          type: string
          description: The object name.
        tags:
          type: array
          description: The tags (i.e. labels).
          example: Address
          items:
            type: string
            description: The tags (i.e. labels).
            example: Address
        type:
          type: string
          description: The type of the channel.
          enum:
          - EMAIL
          - MOBILE
          - WEBSITE
          - CTV
        visitorCount:
          type: integer
          format: int32
          description: The visitor count of the channel.
    UserBean:
      type: object
      description: BlueConic user.
      properties:
        fullName:
          type: string
          description: The full name of the user.
        userName:
          type: string
          description: The username.
      readOnly: true
    ChannelsV2Schema:
      type: object
      properties:
        channels:
          type: array
          description: The channels.
          items:
            $ref: '#/components/schemas/ChannelBeanV2SchemaForChannelsV2'
        itemsPerPage:
          type: integer
          format: int32
          description: Number of results per page.
          readOnly: true
        startIndex:
          type: integer
          format: int32
          description: The start index.
          readOnly: true
        totalPages:
          type: integer
          format: int32
          description: The total number of pages.
          readOnly: true
        totalResults:
          type: integer
          format: int32
          description: The total number of results.
          readOnly: true
  securitySchemes:
    oauth2:
      type: oauth2
      description: 'Authenticates a registered OAuth 2.0 client. The Authorization code flow and Client credentials flow are supported. Make sure to select the correct flow based on which flow the registered client supports. The client id and client secret can be found in BlueConic by opening the registered client under *Settings* > *Access management* > *Applications*.<br/>**NOTE:** When using the Authorization code flow, the redirect URL of the registered client in BlueConic must be set to `https://rest.apidoc.blueconic.com/oauth-receiver.html` and ''Send Proof Key for Code Exchange'' must be enabled.<br/><br/>To use a Bearer token for authentication, follow these steps: <br/>1. Acquire the token through authentication.<br/>2. Include the token in the request''s Authorization header as Bearer \<token\>.<br/>3. Send the request to access protected resources.<br/>4. Handle token expiration by refreshing or obtaining a new token.'
      flows:
        clientCredentials:
          tokenUrl: /rest/v2/oauth/token
        authorizationCode:
          authorizationUrl: /rest/v2/oauth/authorize
          tokenUrl: /rest/v2/oauth/token
          refreshUrl: /rest/v2/oauth/token
