openapi: 3.2.0
info:
  title: BlueConic REST API v2 Profile events API
  description: Welcome to the BlueConic REST API v2.
  termsOfService: https://www.blueconic.com/blueconic-terms-and-conditions
  contact:
    name: Contact us
    url: https://support.blueconic.com/hc/en-us/requests/new
  license:
    name: BlueConic
    url: https://github.com/blueconic/openapi/blob/main/LICENSE.MD
  version: '100.0'
servers:
- url: https://{blueconicHostname}/rest/v2
  description: The BlueConic server
  variables:
    blueconicHostname:
      description: BlueConic server hostname, e.g. 'tenant.blueconic.net'
      default: tenantname
tags:
- name: Profile events
  description: Consent management events for a profile; consent changed or permission level changed. Read more about using Objectives for privacy and consent.
paths:
  /profileEvents/{profileId}:
    get:
      tags:
      - Profile events
      summary: Get profile events
      description: Retrieves the consent management events for a profile; consent changed or permission level changed.
      operationId: getProfileEvents
      parameters:
      - name: profileId
        in: path
        required: true
        schema:
          type: string
          format: uuid
        examples:
          BlueConic Profile UUID:
            description: BlueConic Profile UUID
            value: f448c035-92c1-44d9-810e-40dbf869285f
      - name: startIndex
        in: query
        description: Specifies the index of the first item to include in the result.
        schema:
          type: integer
          format: int32
          default: 0
        example: 0
      - name: count
        in: query
        description: Specifies the number of results to return.
        schema:
          type: integer
          format: int32
          default: 20
        example: 20
      responses:
        '200':
          description: Returns the events.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/profileEvents'
              examples:
                Example profile events response:
                  description: Example profile events response
                  value: "{\n  \"events\": [\n    {\n      \"date\": \"2022-08-13T19:35:21.951Z\",\n      \"properties\": [\n        {\n          \"id\": \"FromRefused\",\n          \"values\": []\n        },\n        {\n          \"id\": \"ToConsented\",\n          \"values\": [\n            \"TestBlueConic\"\n          ]\n        },\n        {\n          \"id\": \"Message\",\n          \"values\": [\n            \"REST API - Update single profile\"\n          ]\n        },\n        {\n          \"id\": \"ToRefused\",\n          \"values\": []\n        },\n        {\n          \"id\": \"FromConsented\",\n          \"values\": []\n        },\n        {\n          \"id\": \"FromLegislation\",\n          \"values\": [\n            \"NONE\"\n          ]\n        },\n        {\n          \"id\": \"ToLegislation\",\n          \"values\": [\n            \"GDPR\"\n          ]\n        },\n        {\n          \"id\": \"Source\",\n          \"values\": [\n            \"REST\"\n          ]\n        }\n      ],\n      \"type\": \"ConsentChanged\"\n    },\n    {\n      \"date\": \"2023-05-04T11:36:25.531Z\",\n      \"properties\": [\n        {\n          \"id\": \"FromRefused\",\n          \"values\": [\n            \"dialogue_objective\"\n          ]\n        },\n        {\n          \"id\": \"ToConsented\",\n          \"values\": [\n            \"dialogue_objective\"\n          ]\n        },\n        {\n          \"id\": \"ToRefused\",\n          \"values\": []\n        },\n        {\n          \"id\": \"Referrer\",\n          \"values\": [\n            \"https://www.blueconic.test/\"\n          ]\n        },\n        {\n          \"id\": \"FromConsented\",\n          \"values\": []\n        },\n        {\n          \"id\": \"FromLegislation\",\n          \"values\": [\n            \"GDPR\"\n          ]\n        },\n        {\n          \"id\": \"ToLegislation\",\n          \"values\": [\n            \"GDPR\"\n          ]\n        },\n        {\n          \"id\": \"Source\",\n          \"values\": [\n            \"CLIENTSIDE\"\n          ]\n        }\n      ],\n      \"type\": \"ConsentChanged\"\n    },\n    {\n      \"date\": \"2023-05-04T11:39:07.652Z\",\n      \"properties\": [\n        {\n          \"id\": \"FromRefused\",\n          \"values\": []\n        },\n        {\n          \"id\": \"ToConsented\",\n          \"values\": [\n            \"dialogue_objective\",\n            \"track_number_of_visits\"\n          ]\n        },\n        {\n          \"id\": \"ToRefused\",\n          \"values\": []\n        },\n        {\n          \"id\": \"Referrer\",\n          \"values\": [\n            \"https://www.blueconic.test/\"\n          ]\n        },\n        {\n          \"id\": \"FromConsented\",\n          \"values\": [\n            \"dialogue_objective\"\n          ]\n        },\n        {\n          \"id\": \"FromLegislation\",\n          \"values\": [\n            \"GDPR\"\n          ]\n        },\n        {\n          \"id\": \"ToLegislation\",\n          \"values\": [\n            \"GDPR\"\n          ]\n        },\n        {\n          \"id\": \"Source\",\n          \"values\": [\n            \"CLIENTSIDE\"\n          ]\n        }\n      ],\n      \"type\": \"ConsentChanged\"\n    },\n    {\n      \"date\": \"2023-05-04T12:43:37.990Z\",\n      \"properties\": [\n        {\n          \"id\": \"FromLevel\",\n          \"values\": [\n            \"PERSONAL\"\n          ]\n        },\n        {\n          \"id\": \"Message\",\n          \"values\": [\n            \"Set by  (1f6961ad-f121-404c-9161-419183f81fc2)\"\n          ]\n        },\n        {\n          \"id\": \"ToLevel\",\n          \"values\": [\n            \"PERSONAL\"\n          ]\n        },\n        {\n          \"id\": \"Source\",\n          \"values\": [\n            \"CLIENTSIDE\"\n          ]\n        },\n        {\n          \"id\": \"Referrer\",\n          \"values\": [\n            \"https://www.blueconic.test/tenants/bc01s01.html\"\n          ]\n        }\n      ],\n      \"type\": \"PermissionLevelChanged\"\n    }\n  ],\n  \"itemsPerPage\": 20,\n  \"startIndex\": 0,\n  \"totalPages\": 1,\n  \"totalResults\": 4\n}"
        '401':
          description: Authentication failed (unauthorized).
        '404':
          description: The profile doesn't exist.
        '503':
          description: The server is too busy to handle the request.
      security:
      - oauth2:
        - read:profiles
components:
  schemas:
    profileEvent:
      type: object
      properties:
        date:
          type: string
          description: Datetime in UTC when the event occurred. The date is in the https://www.ietf.org/rfc/rfc3339.txt format, example = "2025-01-22T11:21:33.872Z".
        property:
          type: array
          items:
            $ref: '#/components/schemas/property'
        type:
          type: string
          description: The type of event.
          enum:
          - PermissionLevelChanged
          - ConsentChanged
    profileEvents:
      type: object
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/profileEvent'
        itemsPerPage:
          type: integer
          format: int32
          description: Number of results per page.
          readOnly: true
        startIndex:
          type: integer
          format: int32
          description: The start index.
          readOnly: true
        totalPages:
          type: integer
          format: int32
          description: The total number of pages.
          readOnly: true
        totalResults:
          type: integer
          format: int32
          description: The total number of results.
          readOnly: true
    property:
      type: object
      description: A property consisting of an ID and a list of values.
      properties:
        id:
          type: string
          description: The ID of the property.
        values:
          type: array
          description: Values for this property.
          items:
            type: string
            description: Values for this property.
  securitySchemes:
    oauth2:
      type: oauth2
      description: 'Authenticates a registered OAuth 2.0 client. The Authorization code flow and Client credentials flow are supported. Make sure to select the correct flow based on which flow the registered client supports. The client id and client secret can be found in BlueConic by opening the registered client under *Settings* > *Access management* > *Applications*.<br/>**NOTE:** When using the Authorization code flow, the redirect URL of the registered client in BlueConic must be set to `https://rest.apidoc.blueconic.com/oauth-receiver.html` and ''Send Proof Key for Code Exchange'' must be enabled.<br/><br/>To use a Bearer token for authentication, follow these steps: <br/>1. Acquire the token through authentication.<br/>2. Include the token in the request''s Authorization header as Bearer \<token\>.<br/>3. Send the request to access protected resources.<br/>4. Handle token expiration by refreshing or obtaining a new token.'
      flows:
        clientCredentials:
          tokenUrl: /rest/v2/oauth/token
        authorizationCode:
          authorizationUrl: /rest/v2/oauth/authorize
          tokenUrl: /rest/v2/oauth/token
          refreshUrl: /rest/v2/oauth/token
