openapi: 3.2.0
info:
  title: BlueConic REST API v2 Objectives API
  description: Welcome to the BlueConic REST API v2.
  termsOfService: https://www.blueconic.com/blueconic-terms-and-conditions
  contact:
    name: Contact us
    url: https://support.blueconic.com/hc/en-us/requests/new
  license:
    name: BlueConic
    url: https://github.com/blueconic/openapi/blob/main/LICENSE.MD
  version: '100.0'
servers:
- url: https://{blueconicHostname}/rest/v2
  description: The BlueConic server
  variables:
    blueconicHostname:
      description: BlueConic server hostname, e.g. 'tenant.blueconic.net'
      default: tenantname
tags:
- name: Objectives
  description: Objectives are used to group items needed for your marketing objectives. When consent is required, items in the objective only get access to profiles that have given consent to the objective. Read more
paths:
  /objectives:
    get:
      tags:
      - Objectives
      summary: Get all objectives
      description: Retrieves all objectives.
      operationId: getAllObjectives
      parameters:
      - name: count
        in: query
        description: Specifies the number of results to return.
        schema:
          type: integer
          format: int64
          default: 20
          example: 10
      - name: startIndex
        in: query
        description: Specifies the index of the first item to include in the result.
        schema:
          type: integer
          format: int64
          default: 0
          example: 0
      responses:
        '200':
          description: Returns all objectives.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/objectives'
              examples:
                Response body:
                  description: Response body
                  value: "{\n  \"itemsPerPage\" : 20,\n  \"objectives\" : [ {\n    \"consentedProfileCount\" : 0,\n    \"creationDate\" : \"2025-09-26T09:05:19.717Z\",\n    \"creator\" : {\n      \"fullName\" : \"ondemand@blueconic.com\",\n      \"userName\" : \"ondemand@blueconic.com\"\n    },\n    \"description\" : \"\",\n    \"id\" : \"marketing_objective\",\n    \"lastModifiedDate\" : \"2025-09-26T09:07:25.493Z\",\n    \"lastModifiedUser\" : {\n      \"fullName\" : \"ondemand@blueconic.com\",\n      \"userName\" : \"ondemand@blueconic.com\"\n    },\n    \"legislations\" : [ \"PIPEDA\", \"JAMAICA_DPA\", \"GDPR\" ],\n    \"lastProfileMutationDate\": \"2025-11-27T10:43:58.004Z\",\n    \"name\" : \"marketing_objective\",\n    \"needsConsent\" : true,\n    \"objectiveDescription\" : \"For marketing purposes\",\n    \"references\" : [ {\n      \"id\" : \"listenerinteractiontype\",\n      \"type\" : \"plugin\"\n    }, {\n      \"id\" : \"f3f2b6fb-7364-4d26-a1ee-7e38704f2869\",\n      \"type\" : \"notebook\"\n    }, {\n      \"id\" : \"6e264f9d-4305-426e-9a7e-7e6ec9b2a18c\",\n      \"type\" : \"dialogue\"\n    }, {\n      \"id\" : \"f9bfadec-2f16-4638-a7e2-8702ba8adad0\",\n      \"type\" : \"segment\"\n    }, {\n      \"id\" : \"ce560586-2452-4830-af34-3edb3528a471\",\n      \"type\" : \"connection\"\n    }, {\n      \"id\" : \"9a9e687c-b889-47a8-bb4a-26bd89972676\",\n      \"type\" : \"listener\"\n    } ],\n    \"refusedProfileCount\" : 0,\n    \"tags\" : [ ],\n    \"title\" : \"Marketing objective\",\n    \"totalProfileCount\" : 0\n  } ],\n  \"startIndex\" : 0,\n  \"totalPages\" : 1,\n  \"totalResults\" : 1\n}"
        '401':
          description: Authentication failed (unauthorized).
        '403':
          description: Authorization failed (incorrect permissions).
        '503':
          description: The server is too busy to handle the request.
      security:
      - oauth2:
        - read:objectives
  /objectives/{objective}:
    get:
      tags:
      - Objectives
      summary: Get one objective
      description: Retrieves a single objective.
      operationId: getOneObjective
      parameters:
      - name: objective
        in: path
        description: The id of the objective to retrieve.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Returns the objective.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/objective'
              examples:
                Response body:
                  description: Response body
                  value: "{\n  \"consentedProfileCount\" : 0,\n  \"creationDate\" : \"2025-09-26T09:05:19.717Z\",\n  \"creator\" : {\n    \"fullName\" : \"ondemand@blueconic.com\",\n    \"userName\" : \"ondemand@blueconic.com\"\n  },\n  \"description\" : \"\",\n  \"id\" : \"marketing_objective\",\n  \"lastModifiedDate\" : \"2025-09-26T09:07:25.493Z\",\n  \"lastModifiedUser\" : {\n    \"fullName\" : \"ondemand@blueconic.com\",\n    \"userName\" : \"ondemand@blueconic.com\"\n  },\n  \"legislations\" : [ \"PIPEDA\", \"JAMAICA_DPA\", \"GDPR\" ],\n  \"lastProfileMutationDate\": \"2025-11-27T10:43:58.004Z\",\n  \"name\" : \"marketing_objective\",\n  \"needsConsent\" : true,\n  \"objectiveDescription\" : \"For marketing purposes\",\n  \"references\" : [ {\n    \"id\" : \"f9bfadec-2f16-4638-a7e2-8702ba8adad0\",\n    \"type\" : \"segment\"\n  }, {\n    \"id\" : \"listenerinteractiontype\",\n    \"type\" : \"plugin\"\n  }, {\n    \"id\" : \"9a9e687c-b889-47a8-bb4a-26bd89972676\",\n    \"type\" : \"listener\"\n  }, {\n    \"id\" : \"6e264f9d-4305-426e-9a7e-7e6ec9b2a18c\",\n    \"type\" : \"dialogue\"\n  }, {\n    \"id\" : \"f3f2b6fb-7364-4d26-a1ee-7e38704f2869\",\n    \"type\" : \"notebook\"\n  }, {\n    \"id\" : \"ce560586-2452-4830-af34-3edb3528a471\",\n    \"type\" : \"connection\"\n  } ],\n  \"refusedProfileCount\" : 0,\n  \"tags\" : [ ],\n  \"title\" : \"Marketing objective\",\n  \"totalProfileCount\" : 0\n}"
        '401':
          description: Authentication failed (unauthorized).
        '403':
          description: Authorization failed (incorrect permissions).
        '404':
          description: The objective doesn't exist.
        '503':
          description: The server is too busy to handle the request.
      security:
      - oauth2:
        - read:objectives
components:
  schemas:
    reference:
      type: object
      description: The items that this objective applies to.
      properties:
        id:
          type: string
          description: The ID of the referenced object
        type:
          type: string
          description: The type of the referenced object
    UserBean:
      type: object
      description: BlueConic user.
      properties:
        fullName:
          type: string
          description: The full name of the user.
        userName:
          type: string
          description: The username.
      readOnly: true
    objectives:
      type: object
      properties:
        itemsPerPage:
          type: integer
          format: int32
          description: Number of results per page.
          readOnly: true
        objectives:
          type: array
          items:
            $ref: '#/components/schemas/objective'
        startIndex:
          type: integer
          format: int32
          description: The start index.
          readOnly: true
        totalPages:
          type: integer
          format: int32
          description: The total number of pages.
          readOnly: true
        totalResults:
          type: integer
          format: int32
          description: The total number of results.
          readOnly: true
    objective:
      type: object
      properties:
        consentedProfileCount:
          type: integer
          format: int64
          description: The number of profiles that consented this objective.
        creationDate:
          type: string
          format: date-time
          description: The creation date of the object. Datetime in UTC in the https://www.ietf.org/rfc/rfc3339.txt format, example = "2025-01-22T11:21:33.872Z".
          readOnly: true
        creator:
          $ref: '#/components/schemas/UserBean'
        description:
          type: string
          description: The description.
        id:
          type: string
          description: The object ID.
        lastModifiedDate:
          type: string
          format: date-time
          description: The last modified date of the object. Datetime in UTC in the https://www.ietf.org/rfc/rfc3339.txt format, example = "2025-01-22T11:21:33.872Z".
          readOnly: true
        lastModifiedUser:
          $ref: '#/components/schemas/UserBean'
        lastProfileMutationDate:
          type: string
          format: date-time
          description: The last time a profile consented the objective. Updated once per hour.
          readOnly: true
        legislations:
          type: array
          description: The legislations this objectives applies to.
          example: '[GDPR, CCPA]'
          items:
            type: string
            description: The legislations this objectives applies to.
            example: '[GDPR, CCPA]'
        name:
          type: string
          description: The object name.
        needsConsent:
          type: boolean
          default: false
          description: Indicates whether this objective requires consent.
          example: true
        objectiveDescription:
          type: string
          description: The description of the objective.
          example: For marketing purposes, to personalize content.
        references:
          type: array
          description: The items that this objective applies to.
          items:
            $ref: '#/components/schemas/reference'
        refusedProfileCount:
          type: integer
          format: int64
          description: The number of profiles that refused this objective.
        tags:
          type: array
          description: The tags (i.e. labels).
          example: Address
          items:
            type: string
            description: The tags (i.e. labels).
            example: Address
        title:
          type: string
          description: The title of the objective.
          example: Personalization
        totalProfileCount:
          type: integer
          format: int64
          description: The number of profiles that have refused or consented this objective.
  securitySchemes:
    oauth2:
      type: oauth2
      description: 'Authenticates a registered OAuth 2.0 client. The Authorization code flow and Client credentials flow are supported. Make sure to select the correct flow based on which flow the registered client supports. The client id and client secret can be found in BlueConic by opening the registered client under *Settings* > *Access management* > *Applications*.<br/>**NOTE:** When using the Authorization code flow, the redirect URL of the registered client in BlueConic must be set to `https://rest.apidoc.blueconic.com/oauth-receiver.html` and ''Send Proof Key for Code Exchange'' must be enabled.<br/><br/>To use a Bearer token for authentication, follow these steps: <br/>1. Acquire the token through authentication.<br/>2. Include the token in the request''s Authorization header as Bearer \<token\>.<br/>3. Send the request to access protected resources.<br/>4. Handle token expiration by refreshing or obtaining a new token.'
      flows:
        clientCredentials:
          tokenUrl: /rest/v2/oauth/token
        authorizationCode:
          authorizationUrl: /rest/v2/oauth/authorize
          tokenUrl: /rest/v2/oauth/token
          refreshUrl: /rest/v2/oauth/token
