openapi: 3.2.0
info:
  title: BlueConic REST API v2 Plugins API
  description: Welcome to the BlueConic REST API v2.
  termsOfService: https://www.blueconic.com/blueconic-terms-and-conditions
  contact:
    name: Contact us
    url: https://support.blueconic.com/hc/en-us/requests/new
  license:
    name: BlueConic
    url: https://github.com/blueconic/openapi/blob/main/LICENSE.MD
  version: '100.0'
servers:
- url: https://{blueconicHostname}/rest/v2
  description: The BlueConic server
  variables:
    blueconicHostname:
      description: BlueConic server hostname, e.g. 'tenant.blueconic.net'
      default: tenantname
tags:
- name: Plugins
  description: Retrieve plugins from the gallery, or limit results to installed plugins only. See Plugins.
paths:
  /plugins/{plugin}:
    get:
      tags:
      - Plugins
      summary: Get one plugin
      description: Retrieves a single plugin
      operationId: getOnePlugin
      parameters:
      - name: plugin
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Returns the plugins.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plugin'
              examples:
                Response body:
                  description: Response body
                  value: "{\n  \"URL\": \"http://plugins.blueconic.net/connection_facebook_ads/5.5.0/connection_facebook_ads.xml\",\n  \"channelTypes\": [\n    \"WEBSITE\"\n  ],\n  \"creationDate\": \"2025-09-30T13:51:12.555Z\",\n  \"description\": \"\",\n  \"descriptions\": [\n    {\n      \"key\": \"en_US\",\n      \"value\": \"\\\\nSend data from BlueConic to Facebook Advertising to enrich Facebook profiles or to target audiences on Facebook and Instagram. Supports conversion API, pixel implementation, and custom audience sync.<br /> Make sure you have no active ad blocker when configuring this connection.<br /> <a href=\\\\\"https://support.blueconic.com/hc/en-us/articles/205377811-Facebook-Advertising-Connection?utm_source=BlueConic_User\\\\\" target=\\\\\"_blank\\\\\">Read more</a>    \"\n    }\n  ],\n  \"id\": \"connection_facebook_ads\",\n  \"indexURL\": \"http://plugins.blueconic.net/connection_facebook_ads/index.xml\",\n  \"labels\": [\n    {\n      \"key\": \"en_US\",\n      \"value\": \"Facebook Advertising connection\"\n    }\n  ],\n  \"lastModifiedDate\": \"2025-09-30T13:51:12.555Z\",\n  \"latestVersion\": true,\n  \"name\": \"connection_facebook_ads\",\n  \"positionType\": \"\",\n  \"profileIndependent\": false,\n  \"scheduleMode\": \"SCHEDULED\",\n  \"supportLevel\": \"STANDARD\",\n  \"tags\": [],\n  \"type\": \"batchconnection\",\n  \"version\": \"5.5.0\"\n}"
        '401':
          description: Authentication failed (unauthorized).
        '403':
          description: Authorization failed (incorrect permissions).
        '404':
          description: The plugin doesn't exist.
        '503':
          description: The server is too busy to handle the request.
      security:
      - oauth2:
        - read:plugins
  /plugins:
    get:
      tags:
      - Plugins
      summary: Get all plugins
      description: Retrieves all plugins.
      operationId: getAllPlugins
      parameters:
      - name: startIndex
        in: query
        description: Specifies the index of the first item to include in the result.
        schema:
          type: integer
          format: int64
          default: 0
          example: 0
      - name: count
        in: query
        description: Specifies the number of results to return.
        schema:
          type: integer
          format: int64
          default: 20
          example: 10
      - name: filterType
        in: query
        schema:
          type: string
      - name: onlyWithPermission
        in: query
        description: If true, only plugins that you have all permissions for are returned.
        schema:
          type: boolean
      - name: includeGallery
        in: query
        description: If true, plugins from the gallery that are not installed are returned.
        schema:
          type: boolean
      - name: locale
        in: query
        description: Locale used for labels and descriptions.
        schema:
          type: string
      - name: channelTypes
        in: query
        description: Only show plugins that have a matching channel type (one or more).
        schema:
          type: string
          enum:
          - WEBSITE
          - EMAIL
          - MOBILE
          - CTV
      responses:
        '200':
          description: Returns the plugins.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plugin'
              examples:
                Response body:
                  description: Response body
                  value: "{\n  \"itemsPerPage\": 4,\n  \"plugins\": [\n    {\n      \"URL\": \"http://plugins.blueconic.net/analyzer_blueconic/1.0.0/analyzer_blueconic.xml\",\n      \"channelTypes\": [],\n      \"creationDate\": \"2025-09-30T13:50:54.986Z\",\n      \"description\": \"\",\n      \"descriptions\": [],\n      \"id\": \"analyzer_blueconic\",\n      \"indexURL\": \"http://plugins.blueconic.net/analyzer_blueconic/index.xml\",\n      \"labels\": [\n        {\n          \"key\": \"en_US\",\n          \"value\": \"Site Analyzer for BlueConic\"\n        },\n        {\n          \"key\": \"nl_NL\",\n          \"value\": \"Site Analyzer for BlueConic\"\n        }\n      ],\n      \"lastModifiedDate\": \"2025-09-30T13:50:54.986Z\",\n      \"latestVersion\": true,\n      \"name\": \"analyzer_blueconic\",\n      \"positionType\": \"\",\n      \"profileIndependent\": false,\n      \"supportLevel\": \"STANDARD\",\n      \"tags\": [],\n      \"type\": \"globallistener\",\n      \"version\": \"1.0.0\"\n    },\n    {\n      \"URL\": \"http://plugins.blueconic.net/connection/1.0.0/connection.xml\",\n      \"channelTypes\": [],\n      \"creationDate\": \"2025-09-30T13:50:36.248Z\",\n      \"description\": \"\",\n      \"descriptions\": [],\n      \"id\": \"connection\",\n      \"indexURL\": \"http://plugins.blueconic.net/connection/index.xml\",\n      \"labels\": [],\n      \"lastModifiedDate\": \"2025-09-30T13:50:36.248Z\",\n      \"latestVersion\": true,\n      \"name\": \"connection\",\n      \"supportLevel\": \"STANDARD\",\n      \"tags\": [],\n      \"type\": \"parameter\",\n      \"version\": \"1.0.0\"\n    },\n    {\n      \"URL\": \"http://plugins.blueconic.net/connection_facebook_ads/5.5.0/connection_facebook_ads.xml\",\n      \"channelTypes\": [\n        \"WEBSITE\"\n      ],\n      \"creationDate\": \"2025-09-30T13:51:12.555Z\",\n      \"description\": \"\",\n      \"descriptions\": [\n        {\n          \"key\": \"en_US\",\n          \"value\": \"\\\\nSend data from BlueConic to Facebook Advertising to enrich Facebook profiles or to target audiences on Facebook and Instagram. Supports conversion API, pixel implementation, and custom audience sync.<br /> Make sure you have no active ad blocker when configuring this connection.<br /> <a href=\\\\\"https://support.blueconic.com/hc/en-us/articles/205377811-Facebook-Advertising-Connection?utm_source=BlueConic_User\\\\\" target=\\\\\"_blank\\\\\">Read more</a>    \"\n        }\n      ],\n      \"id\": \"connection_facebook_ads\",\n      \"indexURL\": \"http://plugins.blueconic.net/connection_facebook_ads/index.xml\",\n      \"labels\": [\n        {\n          \"key\": \"en_US\",\n          \"value\": \"Facebook Advertising connection\"\n        }\n      ],\n      \"lastModifiedDate\": \"2025-09-30T13:51:12.555Z\",\n      \"latestVersion\": true,\n      \"name\": \"connection_facebook_ads\",\n      \"positionType\": \"\",\n      \"profileIndependent\": false,\n      \"scheduleMode\": \"SCHEDULED\",\n      \"supportLevel\": \"STANDARD\",\n      \"tags\": [],\n      \"type\": \"batchconnection\",\n      \"version\": \"5.5.0\"\n    },\n    {\n      \"URL\": \"http://plugins.blueconic.net/contentinteractiontype/1.4.0/contentinteractiontype.xml\",\n      \"channelTypes\": [\n        \"WEBSITE\"\n      ],\n      \"creationDate\": \"2025-09-30T13:50:37.680Z\",\n      \"description\": \"\",\n      \"descriptions\": [\n        {\n          \"key\": \"en_US\",\n          \"value\": \"\\\\n      \\\\n        A 'Content' interaction allows you to replace content on a web-based channel. <a href=\\\\\"https://support.blueconic.com/hc/en-us/articles/202421572-Content-Action-?utm_source=BlueConic_User\\\\\" target=\\\\\"_blank\\\\\">Read more</a>\\\\n     \\\\n    \"\n        }\n      ],\n      \"id\": \"contentinteractiontype\",\n      \"indexURL\": \"http://plugins.blueconic.net/contentinteractiontype/index.xml\",\n      \"labels\": [\n        {\n          \"key\": \"en_US\",\n          \"value\": \"Content\"\n        }\n      ],\n      \"lastModifiedDate\": \"2025-09-30T13:50:37.680Z\",\n      \"latestVersion\": true,\n      \"name\": \"contentinteractiontype\",\n      \"positionType\": \"position\",\n      \"profileIndependent\": false,\n      \"supportLevel\": \"STANDARD\",\n      \"tags\": [],\n      \"type\": \"action\",\n      \"version\": \"1.4.0\"\n    }\n  ],\n  \"startIndex\": 0,\n  \"totalPages\": 20,\n  \"totalResults\": 98\n}"
        '401':
          description: Authentication failed (unauthorized).
        '403':
          description: Authorization failed (incorrect permissions).
        '503':
          description: The server is too busy to handle the request.
      security:
      - oauth2:
        - read:plugins
components:
  schemas:
    DescriptionLabel:
      type: object
      description: 'Localized description text displayed in the About section of the plugin. Provides a brief summary of the plugin’s purpose or functionality. Note: the UI always displays the description with the key set to en_US.'
      properties:
        key:
          type: string
          description: Language code that specifies the locale of the description text. Follows the IETF BCP 47 format (e.g., en_US for U.S. English)
        value:
          type: string
          description: The localized description text for the specified language.
    UserBean:
      type: object
      description: BlueConic user.
      properties:
        fullName:
          type: string
          description: The full name of the user.
        userName:
          type: string
          description: The username.
      readOnly: true
    plugin:
      type: object
      properties:
        URL:
          type: string
          description: The URL of the plugin.
        channelTypes:
          type: array
          items:
            type: string
            enum:
            - WEBSITE
            - FACEBOOK
            - EMAIL
            - MOBILE
            - CTV
        creationDate:
          type: string
          format: date-time
          description: The creation date of the plugin. Datetime in UTC in the https://www.ietf.org/rfc/rfc3339.txt format, example = "2025-01-22T11:21:33.872Z".
        creator:
          $ref: '#/components/schemas/UserBean'
        description:
          type: string
          description: The description of the plugin.
        descriptions:
          type: array
          description: 'Localized description text displayed in the About section of the plugin. Provides a brief summary of the plugin’s purpose or functionality. Note: the UI always displays the description with the key set to en_US.'
          items:
            $ref: '#/components/schemas/DescriptionLabel'
          uniqueItems: true
        id:
          type: string
          description: The ID of the plugin.
        indexURL:
          type: string
          description: The index url of the plugin.
        labels:
          type: array
          description: 'Localized display name of the plugin. Note: the UI always displays the description with the key set to en_US.'
          items:
            $ref: '#/components/schemas/Label'
          uniqueItems: true
        lastModifiedDate:
          type: string
          format: date-time
          description: The last modified date of the plugin. Datetime in UTC in the https://www.ietf.org/rfc/rfc3339.txt format, example = "2025-01-22T11:21:33.872Z".
        lastModifiedUser:
          $ref: '#/components/schemas/UserBean'
        latestVersion:
          type: boolean
          description: Whether this is the latest version of the plugin.
        name:
          type: string
          description: The name of the plugin.
        scheduleMode:
          type: string
          enum:
          - SCHEDULED
          - CONTINUOUS
        supportLevel:
          type: string
          description: The support level of the plugin.
        type:
          type: string
          description: The type of the plugin.
        version:
          type: string
          description: The version of the plugin.
    Label:
      type: object
      description: 'Localized display name of the plugin. Note: the UI always displays the description with the key set to en_US.'
      properties:
        key:
          type: string
          description: Language code that specifies the locale of the labels text. Follows the IETF BCP 47 format (e.g., en_US for U.S. English)
        value:
          type: string
          description: The localized display name for the specified language.
  securitySchemes:
    oauth2:
      type: oauth2
      description: 'Authenticates a registered OAuth 2.0 client. The Authorization code flow and Client credentials flow are supported. Make sure to select the correct flow based on which flow the registered client supports. The client id and client secret can be found in BlueConic by opening the registered client under *Settings* > *Access management* > *Applications*.<br/>**NOTE:** When using the Authorization code flow, the redirect URL of the registered client in BlueConic must be set to `https://rest.apidoc.blueconic.com/oauth-receiver.html` and ''Send Proof Key for Code Exchange'' must be enabled.<br/><br/>To use a Bearer token for authentication, follow these steps: <br/>1. Acquire the token through authentication.<br/>2. Include the token in the request''s Authorization header as Bearer \<token\>.<br/>3. Send the request to access protected resources.<br/>4. Handle token expiration by refreshing or obtaining a new token.'
      flows:
        clientCredentials:
          tokenUrl: /rest/v2/oauth/token
        authorizationCode:
          authorizationUrl: /rest/v2/oauth/authorize
          tokenUrl: /rest/v2/oauth/token
          refreshUrl: /rest/v2/oauth/token
